### ISSUE TITLE
Make OSD only appear on the main screen

### ISSUE THREAD

**Issue by pedrocr** [hajdbo/Better-OSD-GNOME-Extension#3]
Congratulations on the extension as it's very useful. I've left a review. I would also like to suggest a new feature. As described in this gnome-shell bug report:

https://gitlab.gnome.org/GNOME/gnome-shell/issues/327

It makes sense to only display the OSD on the internal screen so it doesn't disrupt presentations or videos being shown. I had a quick look at the gnome-shell code and this extensions' and it seems like it would be relatively simple to add as an option to BetterOSD.

**Comment by hajdbo** [comment]
Thank you for your report!
Happy to accept a pull-request if you submit a patch, however it's convenient as it is for my use case.
