### ISSUE TITLE
Option for keeping OSD visible

### ISSUE THREAD

**Issue by LukeCageCodes** [hajdbo/Better-OSD-GNOME-Extension#5]
Hi @hajdbo ,

excellent extension, thank you!

I use a hardware switch (F4 on my laptop) to mute/unmute. During meetings, I do not use the 'software button' (provided by the application, e.g. in Zoom or Google Meet), but just use the F4 button. However, when you use the F4 button, there isn't an indication whether the mic is on or off. Because I couldn't work out how to manipulate the OSD, I therefore use a USB-plug-in LED [blink(1) / blinkstick nano] to indicate when I'm live or not. May sound a bit over the top - but, I have a lot of meetings, with the meeting application in the background while co-working, so I find this really helpful.

Your extension shows how to manipulate OSD, which is really cool. Would it be possible to add an option to keep the 'mic-level' OSD visible indefinitely? I.e., when the mic comes on, the mic-level OSD stays visible indefinitely, until the mic is switched off?

Many thanks!

**Comment by hajdbo** [comment]
Thanks for the kind words!
I think your use case is really specific, so I don't want to work on this, but you are welcome to fork the project and make it better for you.
